#!/bin/bash

REPOS="$1"
REV="$2"

# No environment is passed to svn hook scripts; set paths to external tools explicitly:
WGET=/usr/bin/wget
SVNLOOK=/usr/bin/svnlook

# If your server requires authentication, it is recommended that you set up a .netrc file to store your username and password
# Better yet, since Jenkins v. 1.426, use the generated API Token in place of the password
# See https://wiki.jenkins-ci.org/display/JENKINS/Authenticating+scripted+clients
# Since no environment is passed to hook scripts, you need to set $HOME (where your .netrc lives)
# By convention, this should be the home dir of whichever user is running the svn process (i.e. apache)
HOME=/var/www/

Changes=`$SVNLOOK changed $REPOS -r $REV`
echo $Changes;
#UUID=`$SVNLOOK uuid $REPOS`
#NOTIFY_URL="subversion/${UUID}/notifyCommit?rev=${REV}"
#CRUMB_ISSUER_URL='crumbIssuer/api/xml?xpath=concat(//crumbRequestField,":",//crumb)'

function notifyCI {
	# URL to Hudson/Jenkins server application (with protocol, hostname, port and deployment descriptor if needed)
	CISERVER=$1

	# Check if "[X] Prevent Cross Site Request Forgery exploits" is activated
	# so we can present a valid crumb or a proper header
	HEADER="Content-Type:text/plain;charset=UTF-8"
	#CRUMB=`$WGET --auth-no-challenge --output-document - ${CISERVER}/${CRUMB_ISSUER_URL}`
	#if [ "$CRUMB" != "" ]; then HEADER=$CRUMB; fi
	echo url: ${CISERVER}
	$WGET \
		--user=admin\
		--password=c0bc743249edb30edb81b9cc94adc02a \
		--header $HEADER \
		--post-data "`$SVNLOOK changed --revision $REV $REPOS`" \
		--output-document "-"\
		--timeout=5 \
		${CISERVER} 
#/${NOTIFY_URL}
}

# The code above was placed in a function so you can easily notify multiple Jenkins/Hudson servers:
if [[ $Changes == *"trunk/ApeApi"* ]]
then
	echo "notify ApeApi";
	notifyCI "http://build.archivesportaleurope.net/jenkins/job/ApeApi/build?token=ApeApiSvn"
fi

if [[ $Changes == *"trunk/DashboardRegressionTest"* ]] 
then
	echo "notify RegressionTest";
	notifyCI "http://build.archivesportaleurope.net/jenkins/job/DashboardRegressionTest/build?token=DashboardRegressionTestSVN"
fi
